### ISSUE TITLE
BLT breaks simple Fortran w/ CMake 3.8

### ISSUE THREAD

**Issue by zbeekman** [LLNL/blt#105]
When I include blt in my CMakeLists.txt I get the following error:

```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CXX_LINK_EXECUTABLE
```

I cloned blt from master at 33b5245039eb5c74b58e25ff96c0171a514585e9 before vendoring it in my project.

Without blt, there are no issues. Any thoughts? Should I try the release version?

**Comment by davidbeckingsale** [comment]
Is your project Fortran only?

**Comment by zbeekman** [comment]
Yes

**Comment by zbeekman** [comment]
well, actually C too, but no CXX

**Comment by davidbeckingsale** [comment]
Does it work if you add CXX to the project languages? I'm guessing something we are doing depends on CXX being enabled, even if it isn't used by the parent project.

**Comment by zbeekman** [comment]
Yes that fixes it. It would be great to remove that dependency on the project config.

**Comment by zbeekman** [comment]
Here is a minimal reproducer CMakeLists.txt for your reference:

```cmake
cmake_minimum_required(VERSION 3.8)
set(ENABLE_FORTRAN ON CACHE BOOL "BLT enable Fortran")
project(NEMO CXX C Fortran)

if(NOT BLT_SOURCE_DIR)
  set(BLT_SOURCE_DIR "${CMAKE_SOURCE_DIR}/cmake/blt")
endif()
include(${BLT_SOURCE_DIR}/SetupBLT.cmake)
```

blt is under cmake/blt not simply blt/

**Comment by davidbeckingsale** [comment]
Definitely! Thanks for reporting the issue.

**Comment by zbeekman** [comment]
I have localized this as being a consequence of `ENABLE_GTEST=ON` when the project is not a CXX project. I'm guessing this should at least default to `OFF` unless CXX is enabled via `project()` or `enable_language()` and perhaps it should even be disallowed to be `ON` unless CXX is enabled in the project.
