### ISSUE TITLE
Why are you adding -ffree-form (GFortran)

### ISSUE THREAD

**Issue by zbeekman** [LLNL/blt#106]
I did not ask for `-ffree-form` to be added. This breaks my build. Either let the user control all compiler flags with your wonderful abstraction or at least detect from the file name (i.e. f77 ends in `.f` or `.F`). Letting users manage it would probably be better though. This is a deal breaker for us, unless there is a publicized API in BLT for removing compiler flags and/or setting defaults. The docs don't mention anything though.

**Comment by davidbeckingsale** [comment]
I think that’s a CMake thing - there is a CMAKE_Fortran_FORMAT option.

**Comment by zbeekman** [comment]
Nope, I remove blt and use vanilla CMake, and it goes away.

**Comment by kennyweiss** [comment]
Thank you for the feedback.

We set the value of ``CMAKE_Fortran_FORMAT`` to ``FREE`` here -- https://github.com/LLNL/blt/blob/master/cmake/SetupCompilerOptions.cmake#L331  (The other possible option is ``FIXED``).  I think we set it up this way since we did not yet have a need for the FIXED format in any of our user codes.

I think a simple fix would be to change this line  (on line 331 of  ``cmake/SetupCompilerOptions.cmake``) from:
```cmake
set(CMAKE_Fortran_FORMAT FREE)
```
to this
```cmake
set(CMAKE_Fortran_FORMAT FREE CACHE STRING "Use free-form format by default")
set_property(CMAKE_Fortran_FORMAT PROPERTY STRINGS FIXED FREE)
mark_as_advanced(CMAKE_Fortran_FORMAT)
```
This adds the CMAKE_Fortran_FORMAT variable to the cache, marks it as advanced and provides the available options as a dropdown in cmake-gui.

You can then override this in your project's configuration by explicitly setting a value before setting up blt (e.g. in a host-config or on the command line)
e.g. 
```cmake
# Place this before invoking include(SetupBLT.cmake)
 set(CMAKE_Fortran_FORMAT FIXED CACHE STRING "")
```

Note that when setting a cache variable in cmake, the value will not be overridden unless the ``FORCE`` option is used, see https://cmake.org/cmake/help/v3.8/command/set.html

**Comment by zbeekman** [comment]
Yes, but what if you have mixed free and fixed sources? (as is the case for the project I am working on.) I think setting it at all is a bad idea. Just let the user set it if they need it at all. Most compilers infer it anyway from the source file extension. Happy to submit a PR to remove it being set.

**Comment by cyrush** [comment]
@zbeekman 

For the mixed case, you can also set (override this per source file) using the Fortran_FORMAT property.  https://cmake.org/cmake/help/latest/prop_tgt/Fortran_FORMAT.html

We are setting it b/c we needed it for most of our fortran codes -- but we could add an option to skip setting it.

Can you share what compilers you are using?

**Comment by zbeekman** [comment]
Right now GFortran 7.2; however, the project will mostly be using Intel
17/18 Parallel Studio. Intel is usually extremely permissive so it’s
possible it won’t be an issue with ifort but supporting both compilers is
the goal. An option for not setting fixed vs free would be awesome!

What compilers/naming conventions do your projects use that require it? If
you name fixed source files .f or .F and free form .f90 or .F90 the
compiler should take care of it. I know the standard is silent on the
issue, but it is a defacto convention. Anyone who names source files .f95,
.f03 or .f08 should be talked out of that habit IMO. No one names C, C++ or
other programming language source files after the particular revision of
the langauge’s standard.

Anyway, sorry for the unsolicited, free advice. Keep up the awesome work.

**Comment by cyrush** [comment]
@zbeekman pondered this a bit more, since it's easy to use the cmake settings maybe we shouldnt be setting and undermining folks.  Haven't had a chance to check out your pull request,  but I will try to do so soon.

**Comment by zbeekman** [comment]
That’s the conclusion everyone else who weighed in on the PR came to.
(AFAICT.) I have yet to make the last tweak to implement the proposal, but
the plan is:

- default to setting a BLT option, `FORTRAN_FORMAT` or something like that
to `INFER` which means do nothing, let compiler defaults or custom settings
handle it.
- `FREE` and `FIXED` let users set it globally.

This strikes me as a good balance.

Should get to this change tomorrow.

People had conflicting opinions about whether this option should be marked
advanced. My opinion is we went through the trouble of creating this
convenience option, so you may as well expose it to the user. Furthermore,
I find few users ever use `ccmake` or `cmake-gui` so whether it is marked
as advanced or not is of relatively little consequence.

**Comment by cyrush** [comment]
@zbeekman , I guess I am not sure we need our own option vs the cmake option. 

I know the work has been done, but i am keen to have less maintain.
(sorry I didn't see the pr earlier -- just realized I didn't have notifications  on when @kennyweiss pinged me about the issue)

**Comment by kennyweiss** [comment]
@cyrush -- If free-form w/ ``.f`` extensions is how our local users typically set up their codes, it is probably a good idea to keep the option there, with the three option (``INFER`` (default), ``FREE``, ``FIXED``) so they can see the available option in our documentation.  

Seems like this would lead to easier migration to blt, and, as you mentioned, the work is already done.

**Comment by cyrush** [comment]
@kennyweiss Yes, but if `INFER` Is the default, isn't it one line for folks using BLT for this regardless if there is a BLT option? If thats the case, thats a signal we aren't adding in BLT and making things more complicated. 

If it's more than a one liner for folks to opt in w/out the BLT solution , (again I haven't had time to review in depth), then I can see us keeping it.
