### ISSUE TITLE
BLT version has no associated tag

### ISSUE THREAD

**Issue by gzagaris** [LLNL/blt#11]
There should be a tag on master associated with the BLT version. 

Also, why v0.1? I thought we were employing semantic versioning => MAJOR.MINOR.PATCH

**Comment by davidbeckingsale** [comment]
I agree. The initial commit should be 0.1.0, and current master should be 0.2.0.

**Comment by cyrush** [comment]
@gzagaris tagged the initial release as v0.1.0, and linked this to a github release. 

We will tag next when we decide to do a release (when we get enough features, bug fixes)

**Comment by gzagaris** [comment]
@cyrush thanks -- makes sense.
