### ISSUE TITLE
Accelerate travis 

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#114]
It looks like each job in our travis matrix downloads and installs its own copy of ``gcc-4.9``, ``mpi`` and other dependencies, which adds an overhead of around 5 minutes per job.
See, e.g.: https://travis-ci.org/LLNL/blt/jobs/293314047#L448

Here is the snippet that sets up our addon packages: https://github.com/LLNL/blt/blob/9f178d9a06943a7811a947d4e31def572b3bdda6/.travis.yml#L107-L116

Since we have 10 travis jobs, this delays the turnaround time for quick commits/checks.

It would be great if there was a way to cache the required environment with the correct compilers, mpi, and other TPLs and just use it for our BLT builds.  

Does anyone have experience with this? Perhaps using docker containers?

**Comment by cyrush** [comment]
we could cache these dependencies, but it would come with a lot more complexity than those 10 lines of yml providing those things now. Is this really a barrier?  BLT has the fastest CI turn around of any project I am involved in. 

There are some other things we should check (make sure pushes cancel pending jobs, etc)

**Comment by zbeekman** [comment]
You may be able to get a simpler cach setup with the BETA build stages on Travis-CI: https://docs.travis-ci.com/user/build-stages/. This would cause a common download+install through apt of the dependencies defined in a common build stage, and then you could run each of the tests in parallel on top of this. I haven't tried it myself but it looks like a decent compromise between enabling caching/speedup and complexity in .travis.yml.

**Comment by zbeekman** [comment]
Well my idea was a red herring. The build stages still require an apt-get install for each stage, which is annoying.

**Comment by davidbeckingsale** [comment]
We can fix this with containers 😄 I'll get to this sometime - we are in the process of developing some LC-like containers for just these kind of use cases.

**Comment by rrsettgast** [comment]
@davidbeckingsale From the last exchange we had about getting some LC-like containers, I didn't know you were "in process" on this. I have some CentOS7.5 containers and was going to apply the LC compiler install scripts on those images....should I stop and just wait for you to figure this out?

**Comment by davidbeckingsale** [comment]
Well we have CentOS containers, but it would depend on how LC-like you want them. Since the whole point of the containers to be lightweight, it's not going to be like a full TOSS environment.

**Comment by rrsettgast** [comment]
I think that you wouldn't want them to be full on LC-like TOSS environments. Just the same version of Redhat (TOSS3==>CentOS7.5) and the right compilers setup the way that LC sets them up. Is there something that we are missing if we just have the equivalent OS and compilers?

**Comment by white238** [comment]
#354
