### ISSUE TITLE
Document `blt_register_library`'s interface

### ISSUE THREAD

**Issue by zbeekman** [LLNL/blt#118]
Pls see title.

Feel free to close if this is a duplicate but I didn't find it anywhere after a brief search through your issues. I may help with this once I learn it myself.

**Comment by kennyweiss** [comment]
Thanks @zbeekman -- our documentation is still very much a work in progress, and some of the existing documentation is already out of date.

``blt_register_library`` definitely \*should\* be documented.

In the meantime, the best documentation for our macros can be found in the file itself (``cmake/BLTMacros.cmake``) right before each macro definition.

**Comment by zbeekman** [comment]
Yes, I’ve discovered that. If I have time I’ll submit a documentation PR. I
just wanted to mention it here to keep track
