### ISSUE TITLE
fruit smoke test build error with xlf

### ISSUE THREAD

**Issue by jdahm** [LLNL/blt#128]
I'm running into a compilation error on the smoke test for fruit on the early access systems. I'm not sure if ultimately the blame is with the compiler flags, BLT, or SAMRAI itself, but I thought the team would be able to help. The CMake cache shows that `CMake_Fortran_COMPILER=xlf` for this, and it's adding -qmoddir but from the looks of the man page, it needs `-I${CMAKE_Fortran_MODULE_DIR}` as well to find out where to look for the module files. `blt/cmake/SetupCompilerOptions.cmake` is only considering the C and CXX compilers. Where is the appropriate place to add this reference?

```
cd SAMRAI/blt/tests && /usr/tcetmp/bin/xlf  -ISAMRAI/include -I/usr/tce/packages/cuda/cuda-9.1.85/include  -qthreaded -qhalt=e -g -qmoddir=../../lib/fortran -fPIE   -qfree -c SAMRAI/blt/tests/blt_fruit_smoke.f -o CMakeFiles/blt_fruit_smoke.dir/blt_fruit_smoke.f.o
COMMAND LINE  1520-065 (W) The XLF77(PERSISTENT) option stores entities in static storage.  This may affect the thread safety of your code.
COMMAND LINE  1520-065 (W) The SAVE option stores entities in static storage.  This may affect the thread safety of your code.
COMMAND LINE  1520-022 (W) The FREE option has been replaced by the option FREE(F90).
"SAMRAI/blt/tests/blt_fruit_smoke.f", line 51.7: 1514-219 (S) Unable to access module symbol file for module fruit. Check path and file permissions of file. Use association not done for this module.
1501-511  Compilation failed for file blt_fruit_smoke.f.
```

**Comment by kennyweiss** [comment]
@jdahm -- Are you using the master version of ``blt``?

I encountered this issue a few weeks ago, and added the fortran modules directory as an include flag for fortran executables (see: #125).

Note that the variable in that PR is ``CMAKE_Fortran_MODULE_DIRECTORY``, rather than ``CMAKE_Fortran_MODULE_DIR``.

**Comment by jdahm** [comment]
Ah ha. We were still back on an older commit. Checking out the master branch fixed the issue. Thanks for catching and fixing that before I hit the issue, and for the quick response.

**Comment by kennyweiss** [comment]
No problem. Happy it was so easy to resolve this one.

Also, I noticed that blt's ``host-config`` for this platform does not set an explicit Fortran compiler (we are planning to add more Fortran tests soon).

In case this is helpful, I used the following compiler (from the 10/13 drop):
```cmake
set(CMAKE_Fortran_COMPILER "/usr/tce/packages/xl/xl-beta-2017.10.13/bin/xlf2003" CACHE PATH "")
```
and also added the following linker flags when using ``xlf`` with ``xlc``:
```cmake
# Convert C-style comments to Fortran and link fortran exes to C++ libraries
set(BLT_FORTRAN_FLAGS "-WF,-C! -Wl,-lstdc++ -Wl,/usr/tce/packages/xl/xl-beta-2017.10.13/xlC/13.1.6/lib/libibmc++.so" CACHE STRING "")
```
When using``xlf`` with ``clang`` (also from the 10/13 compiler drop), I needed:
```cmake
# Converts C-style comments to Fortran style in preprocessed files
set(BLT_FORTRAN_FLAGS "-WF,-C!" CACHE STRING "")

# Adds a missing rpath for libraries associated with the fortran compiler
set(BLT_EXE_LINKER_FLAGS "-Wl,-rpath,/usr/tce/packages/xl/xl-beta-2017.10.13/lib" CACHE STRING "")
```

Note:   ``xlf2003`` is a wrapper that adds some additional default flags to the ``xlf`` compiler.  

I will try to update the ``blt`` host-config when I get a chance.

**Comment by jdahm** [comment]
I just hit the error with the missing path myself. In the future I'll use your fix `set(BLT_EXE_LINKER_FLAGS "-Wl,-rpath,/usr/tce/packages/xl/xl-beta-2017.10.13/lib" CACHE STRING "")` updated for the 11/30 drop.
