### ISSUE TITLE
Issue in handling of CUDA headers

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/blt#136]
I'm a little fuzzy on the exact nature of this bug.

I have a piece of source code which a manually constructed Makefile works for, a CMakeLists.txt using CMake 3.8's "CUDA as a language" support works for, but which BLT chokes on. As this was buried in a massive software project, I made a small reproducer [here](https://github.com/DavidPoliakoff/jitify/tree/feature/blt_reproducer) (note the branch if you try to repro).

The error I get looks like

```
jitify.hpp:1898:8: error: expression contains unexpanded parameter pack 'args'
return (this->launch(std::vector< void *> ({((void *)(&args))}), {reflection::reflect< ArgTypes> ()...}));
```

When the code on that line looks like

```
return this->launch(std::vector<void*>({(void*)&args...}), {reflection::reflect<ArgTypes>()...});
```

Which is an expanded parameter pack (look at the first argument to "launch," the original has "an ellipsis" after it). So somewhere between my CMakeLists.txt and the compiler, the code is getting mangled. I'm not sure if it's BLT (seems unlikely) or the CUDA CMake scripts.

A resolution would be some branch of BLT for which the provided CMakeLists.txt works

edit: I've also pinged Max Katz about the problem, he says he can ask around with NVIDIA

**Comment by davidbeckingsale** [comment]
This is caused when the language standard flag is not set correctly when generating the dependency file. I can build your reproducer by explicitly setting `CUDA_NVCC_FLAGS "{CUDA_NVCC_FLAGS} -std=c++11")` in CMakeLists.txt

**Comment by DavidPoliakoff** [comment]
Anybody else spotting this, Beckingsale and I are talking it over in other channels, will report back

**Comment by davidbeckingsale** [comment]
Pinging @trws

**Comment by davidbeckingsale** [comment]
@DavidPoliakoff can you attach the full compile output from both the BLT version and using CMake native CUDA?

**Comment by cyrush** [comment]
is this compiler or system specific? I had to set CUDA_NVCC_FLAGS to add `-std=c++11` for some ibm systems ... 

Without this, I found that FindCUDA stripped the c++11 flag spec.

**Comment by DavidPoliakoff** [comment]
@cyrush , that's what's (part of what's) really weird.

If I use clang I get these issues, if I use g++ I don't (I get different issues, which I don't think are relevant here). 

But the problem I'm getting is that when I use clang I'm getting an entirely different *source file* than I have in my codebase, in an area with no obvious preprocessor shenanigans to cause the issues, in a place where I don't see these issues with CMake 3.8+ native CUDA support. So I don't think that it's a matter of the C++11 flag (actually just verified, that is getting passed along). For reference, the compile line is pretty innocuous

```
/opt/cudatoolkit-9.0/bin/nvcc /usr/workspace/wsrzd/dzpolia/src/jitify/jitify_example.cu -c -o /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//./oops.exe_generated_jitify_example.cu.o -ccbin /usr/global/tools/clang/chaos_5_x86_64_ib/clang-3.8.0/bin/clang++ -m64 -DUSE_CUDA -std=c++11 -DNVCC -I/opt/cudatoolkit-9.0/include -I/usr/workspace/wsrzd/dzpolia/src/jitify
```

Which is why I think it's something in 

```
-- Removing /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//./oops.exe_generated_jitify_example.cu.o
/collab/usr/global/tools/cmake/chaos_5_x86_64_ib/cmake-3.8.2/bin/cmake -E remove /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//./oops.exe_generated_jitify_example.cu.o
-- Generating dependency file: /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.NVCC-depend
/opt/cudatoolkit-9.0/bin/nvcc -M -D__CUDACC__ /usr/workspace/wsrzd/dzpolia/src/jitify/jitify_example.cu -o /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.NVCC-depend -ccbin /usr/global/tools/clang/chaos_5_x86_64_ib/clang-3.8.0/bin/clang++ -m64 -DUSE_CUDA -std=c++11 -DNVCC -I/opt/cudatoolkit-9.0/include -I/usr/workspace/wsrzd/dzpolia/src/jitify
-- Generating temporary cmake readable file: /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend.tmp
/collab/usr/global/tools/cmake/chaos_5_x86_64_ib/cmake-3.8.2/bin/cmake -D input_file:FILEPATH=/usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.NVCC-depend -D output_file:FILEPATH=/usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend.tmp -D verbose=1 -P /usr/workspace/wsrzd/dzpolia/src/jitify/blt/cmake/thirdparty/FindCUDA/make2cmake.cmake
-- Copy if different /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend.tmp to /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend
/collab/usr/global/tools/cmake/chaos_5_x86_64_ib/cmake-3.8.2/bin/cmake -E copy_if_different /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend.tmp /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend
-- Removing /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend.tmp and /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.NVCC-depend
/collab/usr/global/tools/cmake/chaos_5_x86_64_ib/cmake-3.8.2/bin/cmake -E remove /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.depend.tmp /usr/workspace/wsrzd/dzpolia/src/jitify/build/CMakeFiles/oops.exe.dir//oops.exe_generated_jitify_example.cu.o.NVCC-depend
```

This stuff which doesn't exist with native CUDA support

**Comment by DavidPoliakoff** [comment]
@davidbeckingsale , I have a really cool solution for this, we should talk Monday. From my side, this issue can be closed, if somebody else finds this issue through a search and we haven't described a solution feel free to ping me with a comment on this thread

**Comment by DavidPoliakoff** [comment]
@cyrush @davidbeckingsale : check out 

https://github.com/LLNL/RAJAPerf/pull/43

For an example of how to use BLT and native CUDA support.

Q: "But wait, you didn't do anything."
A: "Yes, BLT just plays nicely with native CUDA support."

Only change to note: you MUST enable CUDA as a language in the project line, I haven't found a way around it.

What I'd love is to get some of the CUDA handling from BLT without going through FindCUDA, you do something intelligent in deciding which flags need -Xcompiler before them which I don't get when I don't go through BLT, but otherwise this just works.

Feel free to close this issue, it's now more of a discussion space than a breaking bug

**Comment by davidbeckingsale** [comment]
I think we could do that, but really we need to decide when to support 3.8+ only and dump our usage of FindCUDA....

**Comment by cyrush** [comment]
I am pretty sure we will need at least cmake 3.9, it addressed several issues with native cuda support that were in 3.8

**Comment by DavidPoliakoff** [comment]
Honestly, I don't know BLT well enough to inform the design, I'll answer
any questions, but will leave you with the example and say "go nuts," I
don't know how to support this in a productized way.

**Comment by robinson96** [comment]
@davidbeckingsale @DavidPoliakoff , can you take another look at this - my recent merge has adopted CMAKE's native CUDA support in BLT.  I think this issue may be resolved at this point.

**Comment by DavidPoliakoff** [comment]
@robinson96 : thank you so much for doing this, that resolved my issue. So cool! I consider this resolved, feel free to close it if you don't want any more feedback

**Comment by DavidPoliakoff** [comment]
@rblake-llnl: you were asking about this

**Comment by cyrush** [comment]
Per @robinson96's work + comment above and further vetting, I think this is resolved by using native cmake cuda support.
