### ISSUE TITLE
Fix llnl-ray host-config

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#146]
While working on #145, I found that the CUDA-enabled ``llnl-ray`` host-config is no longer working.  
We should fix this.

### Details:

There is a problem with the ``pthreads`` flags in the CUDA example.

I configured the code with:
```bash
export BLT_ROOT=<path/to/blt/root>

cmake  \
   -C ${BLT_ROOT}/host-configs/llnl-ray-blue_os-gcc\@4.9.3.cmake  \
    ${BLT_ROOT}/tests/internal/
```

The error that I'm getting is:
```bash
[ 95%] Linking CUDA executable ../../bin/t_cuda_device_call_from_kernel_exec
nvcc fatal   : Unknown option 'pthread'
make[2]: *** [src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_exec.dir/build.make:89: bin/t_cuda_device_call_from_kernel_exec] Error 1
make[1]: *** [CMakeFiles/Makefile2:1529: src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_exec.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Notes:
* @cyrush suspects that something in the ``blue_os`` environment changed since this used to work.
* @DavidPoliakoff was able to get the compilation to work by manually changing ``-pthread`` to ``-Xcompiler -pthread`` (thanks David!).  Anyone know where I can make that change?  (preferably in the host-config)

See the discussion in #145 for some additional details.

**Comment by robinson96** [comment]
This is now fixed, and exercises the latest and greatest use of native CMake CUDA support. Surface got updated as well.
