### ISSUE TITLE
linking issues w/ static builds on windows

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#15]
If _BUILD_SHARED_LIBS_ is off on windows --  get we static vs dynamic linking issues related to gtest and gmock.

`gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in blt_gtest_smoke.obj`

gtest and gmock should be using our _BUILD_SHARED_LIBS_ option, so we may need to set some other options (or compiler defines). 

Note: to get shared libs to work, I had to add:

`-DGTEST_CREATE_SHARED_LIBRARY=1`

When compiling gtest and gmock

and 

`-DGTEST_LINKED_AS_SHARED_LIBRARY=1`

for targets linking it

I tried an obvious set of defines (setting those each to 0) for the shared case, but that wasn't the right magic.

**Comment by davidbeckingsale** [comment]
I think this might help: https://github.com/LLNL/RAJA/blob/master/cmake/SetupCompilers.cmake#L72

**Comment by cyrush** [comment]
resolved in #14 , thanks @davidbeckingsale for the solution.
