### ISSUE TITLE
Add clang-query support for targeted code health checks

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#159]
David Poliakoff demoed a good prototype of how to write custom clang-query checkersto Adam Kunen and me.

This is a pragmatic path to support very specific checks for example: find things violating this run inside of a RAJA kernel.

clang-query is a command line tool, it would look similar to using cppcheck or uncrustify.

**Comment by davidbeckingsale** [comment]
This would be cool, especially if we could bundle some (optional) queries with BLT.

**Comment by DavidPoliakoff** [comment]
Hey folks, just an FYI that we've pushed out the prototype for this as part of an L2, I have it working in a fork of LAMMPS. Who would want to be in on a conversation about putting this into BLT?

**Comment by white238** [comment]
Added in #204 ... Belated thanks @DavidPoliakoff !
