### ISSUE TITLE
BLT shouldn't set -DUSE_MPI

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#165]
Projects use all kinds of flags to indicate the presence of mpi

We should remove this from 

https://github.com/LLNL/blt/blob/master/cmake/thirdparty/SetupMPI.cmake

and defer to what users want to do downstream.

**Comment by rrsettgast** [comment]
Just to clarify, is the desire to remove the -DUSE_MPI flag from inclusion in the compilation flags, or undefine the USE_MPI cmake variable?

**Comment by cyrush** [comment]
resolved in #167
