### ISSUE TITLE
Add "-fsandalone-debug" flag to clang debug builds?

### ISSUE THREAD

**Issue by rrsettgast** [LLNL/blt#166]
When using clang, the -fsandalone-debug allows you to dive on objects that are otherwise listed as opaque in totalview. For example you can't inspect the value of std::string without the flag.

http://docs.roguewave.com/totalview/8.15.4/pdfs/totalview%208.15.4-release_notes.pdf page 7

Is this something that should be a default in blt?

**Comment by gzagaris** [comment]
My gut reaction is to handle that at the application level, since it is easily accomplished. Having yet another magic layer that injects compiler flags, albeit useful in some cases, may obfuscate things in other cases.

Just my 2c.

**Comment by rrsettgast** [comment]
I guess the question is....is there a case where an application wouldn't want this flag set?

**Comment by gzagaris** [comment]
That's exactly what I am not certain of and hence lean towards being more conservative. If this flag is harmless, which may very well be the case, it won't matter. If it turns out to be problematic, it may be difficult for an application developer to figure out where and who emits that flag.

**Comment by cyrush** [comment]
@rrsettgast I agree with @gzagaris, this seems like something easily done outside of blt.
blt makes it quite easy to set flags for each compiler in your own cmake logic.

We don't really want to wade into selecting flags, but we are happy to help make that easier for folks using blt.
