### ISSUE TITLE
Failing HAVE_REGEX tests on rzmanta with clang-coral

### ISSUE THREAD

**Issue by corbett5** [LLNL/blt#169]
Chai is failing the HAVE_*_REGEX tests when building with clang-coral-2018.05.23. The error I get is

-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- failed to compile
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
CMake Error at blt/thirdparty_builtin/gbenchmark-master-2017-05-19/CMakeLists.txt:192 (message):
  Failed to determine the source files for the regular expression backend

**Comment by corbett5** [comment]
@davidbeckingsale

**Comment by white238** [comment]
Setup problem.  Closed.
