### ISSUE TITLE
Add support for Clang's CUDA compilation

### ISSUE THREAD

**Issue by davidbeckingsale** [LLNL/blt#17]
Currently, executables and libraries that depend on CUDA will use `nvcc` for compilation. However, these targets could be compiled with clang's native CUDA support.

We need an option to differentiate between clang+cuda where `clang` is the host and `nvcc` is the CUDA compiler, and clang+cuda where `clang` is used for both.

**Comment by davidbeckingsale** [comment]
@cyrush @white238 I'm interested in your opinion on this. Compiling CUDA with clang works more like OpenMP, where you just need some extra compile flags.

I can just use `blt_register_library` for this, and call it `clang_cuda`. 

What do you think the best way of handling all the different combination of options is (dealing with conflicts). For example, nvcc+clang, clang_cuda, a user saying something depends on clang_cuda and cuda etc.

**Comment by cyrush** [comment]
Assuming that folks don't want to use both nvcc and cuda-clang in the same project

(which, while adventurous doesn't seem like a sensible thing to support generally)


I don't think we want folks to have to link cuda, or clang_cuda,

We should figure out a way for either nvcc or clang-cuda to provide  BLT`cuda` and `cuda_runtime` deps.

**Comment by davidbeckingsale** [comment]
That would be easy... he says. Would you be happy with a `mark_as_advanced` option `ENABLE_CLANG_CUDA` that would enable this behavior?

**Comment by cyrush** [comment]
that sounds fine

**Comment by adayton1** [comment]
I think this is completed, unless I'm missing something. Can we close this issue?
