### ISSUE TITLE
add_test macro messes with the COMMAND argument

### ISSUE THREAD

**Issue by davidbeckingsale** [LLNL/blt#18]
The `COMMAND` argument for the add test macro gets modified in a way that doesn't make sense (prepending the `bin` directory to it).

If the user has actually provided a test command they want to run, this will break.

I think we should have two arguments: `EXECUTABLE` and `COMMAND`, that can be joined together when calling CMake's add_test macro. This would allow the user to specify a custom command while also allowing us to find the full path of the executable.

**Comment by zbeekman** [comment]
Might it be possible to just see if the argument passed to `COMMAND` is a target known to CMake? CMake will even let you query the output location for executable targets. If it's not a target then assume it's a script and/or the user knows what their doing.

**Comment by kennyweiss** [comment]
There is some subtle logic in getting this to work with makefile-based generators and with multi-config-based generators like visual studio, see:
https://github.com/LLNL/blt/blob/master/cmake/BLTMacros.cmake#L588-L595

We also have to append the appropriate ``MPIEXEC`` command and arguments for mpi tests (with some modifications for getting testing to work on some of our platforms, e.g. to always wrap tests in ``MPIEXEC``, even when they are not MPI tests).

Definitely open to better ways to do this if it can cover all the existing use cases.

**Comment by white238** [comment]
This is outdated as far as I can tell.
