### ISSUE TITLE
Upgrade flag-related blt macros to work with INTERFACE targets

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#181]
PR #177 updated the ``blt_add_target_compile_flags`` macro to work with ``INTERFACE`` targets.

We can apply a similar upgrade to the ``blt_add_target_definitions`` and ``blt_add_target_link_flags`` macros for ``INTERFACE`` targets.

**Comment by white238** [comment]
blt_add_target_definitions is already fixed.

Maybe I am not understanding something but blt_add_target_link_flags doesn't really make sense for interface targets (you don't link header only libraries). @kennyweiss ?
