### ISSUE TITLE
NUM_PROCS for blt_add_test only supports mpi tests

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#2]
We are also passing for the openmp smoke test, which in turn tries to craft an mpiexe to launch the openmpi test. Which of course is wrong.

From blt_add_test
```
    # Handle mpi
    if ( ${arg_NUM_PROCS} )
        set(test_command ${MPIEXEC} ${MPIEXEC_NUMPROC_FLAG} ${arg_NUM_PROCS} ${test_command} )
    endif()

    add_test(NAME ${arg_NAME}
             COMMAND ${test_command} 
             )


```
If MPI isn't selected all at,  you will see errors messages like the following:

```
    Start 5: blt_openmp_smoke
Could not find executable 2
Looked in the following places:
2
2
Release/2
Release/2
Debug/2
Debug/2
MinSizeRel/2
MinSizeRel/2
RelWithDebInfo/2
RelWithDebInfo/2
Deployment/2
Deployment/2
Development/2
Development/2
Unable to find executable: 2
5/5 Test #5: blt_openmp_smoke .................***Not Run   0.00 sec
```

**Comment by cyrush** [comment]
removed NUM_PROCS arg for openmp test in github PR #1, leaving open for us to decide if we want to actually support num procs for openmp tests.

**Comment by davidbeckingsale** [comment]
It might be useful to factor this into two options: `NUM_RANKS`  for MPI and `NUM_THREADS` for OpenMP tests? Using the same option for both doesn't allow tests that combine MPI and OpenMP.

**Comment by cyrush** [comment]
@davidbeckingsale  agreed -- we will want to want to support both openmp and mpi in the same test -- so we will need explicit options for each case

**Comment by zbeekman** [comment]
If this issue is still open (for real, i.e., not because someone forgot to close it) I would suggest renaming it to reflect the actionable changes that are required. That way impatient users---like me!---might open a PR implementing this. Active language in the title is always good: e.g.,

> "Request for Enhancement (RFE): Add `NUM_RANKS` and `NUM_THREADS` argument to `blt_add_test` macro"

Or

> "Defect: No direct support for multiple OMP threads with `blt_add_test`"

FWIW, +1 for having `NUM_RANKS` & `NUM_THREADS` arguments to `blt_add_test`.

**Comment by cyrush** [comment]
NUM_PROCS was changed to NUM_MPI_TASKS, there are no option for setting the OMP tasks. 

I am actually not sure what that should look like, I suspect folks have been writting tests with the default number of OMP threads.  For MPI you have to be more explicit.

**Comment by cyrush** [comment]
I vote to close this issue, if we like we can open another one for OMP threads.
