### ISSUE TITLE
Have CI test for tutorial docs

### ISSUE THREAD

**Issue by white238** [LLNL/blt#208]
readthedocs wasn't updating because the "make docs" target was failing.  This is an obvious problem and we should add this as a test to each PR.

**Comment by rhornung67** [comment]
@white238 why do you need to use a cmake target to generate readthedocs documentation? You should only need to add a github web hook to your rtd project to have it build the docs when a change is pushed to your repo on any branch marked active in rtd.

**Comment by white238** [comment]
The readthedocs page wasn't being updated and there wasn't any indication that I could see.  My only assumption is because some files moved that were referenced in some "literalinclude" blocks; this is an error. Maybe @cyrush got an email?

**Comment by cyrush** [comment]
@white238 , I don't get emails on rtd errors -- something strange is going on with the build (it says it can't fetch your branches). I can't dig in right now -- but I can add you as a maintainer. Can you link RTD with your github account?

**Comment by white238** [comment]
We solved the RTD problems.  It needed a default branch (no idea where it came up with a now non-existent branch) and added email notifications for failed builds.
