### ISSUE TITLE
MPIEXEC is deprecated in cmake 3.10

### ISSUE THREAD

**Issue by rrsettgast** [LLNL/blt#218]
It appears that ```MPIEXEC``` is deprecated in favor of ```MPIEXEC_EXECUTABLE``` in ```cmake 3.10``` as seen [here](https://cmake.org/cmake/help/v3.10/module/FindMPI.html) . I was having some issues with my builds that may have been related to this, but I did notice that BLT uses ```MPIEXEC``` inside SetupMPI():

https://github.com/LLNL/blt/blob/09173186b693f86e9b5b50ce5f1e61a9c9172ccf/cmake/thirdparty/SetupMPI.cmake#L61

and in blt_add_test()

https://github.com/LLNL/blt/blob/09173186b693f86e9b5b50ce5f1e61a9c9172ccf/cmake/BLTMacros.cmake#L706

Is this something that should be updated?

**Comment by white238** [comment]
I'll pop a branch soon that toggles this based on version. Thanks for the reported issue @rrsettgast !
