### ISSUE TITLE
External executables as targets in tests

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/blt#220]
I'm talking with @manuelmeraz at the new employee coding session, he was asking me a question I don't know the answer to

His testing framework looks like "I run a Python script that isn't made by CMake with different arguments in order to launch tests," with the different arguments defining different tests. In BLTMacros, there's a requirement that either NAME or the first arg in COMMAND be the name of a BLT recognized target.

How would a user implement the workflow this user is looking to do? There's no blt_register_executable to match blt_register_library.

Thanks for any advice

**Comment by white238** [comment]
I agree we shouldn't require blt_add_test to be a CMake target.  To get around this just use CMake's normal [add_test](https://cmake.org/cmake/help/v3.13/command/add_test.html) for this until we fix it.

**Comment by kennyweiss** [comment]
Would it be possible to throw together a mockup of how you'd like to use ``blt_add_test``?

It looks like we only use the CMake target to extract the runtime directory:

https://github.com/LLNL/blt/blob/ac03e8c85eb540cb40fe2fcfc34d764b1f6d8ae0/cmake/BLTMacros.cmake#L677-L686

**Comment by DavidPoliakoff** [comment]
I'll leave answering those to @ManuelMeraz, I don't know the details of his use cases. Thanks for the speedy replies though

**Comment by ManuelMeraz** [comment]
Right, currently I'm doing something like this:

```
set(tests
      test1
      test2)

foreach(test ${tests})
    add_test(NAME test_${test} COMMAND ${some_path}/script.py ${test})
endforeach()
```

So `test1` and `test2` are not executables, but simply test names. The python script is located somewhere above the build directory. 

I guess I could copy the script into build when I compile and call it there, which was what I was thinking. I have a lot of tests that I like to run, and I like to have some extra text appended to the test names when running ctest, but it looks like blt only allows test names that are currently targets. 

Although @DavidPoliakoff suggested I could add targets manually, which I can look into.

**Comment by cyrush** [comment]
@ManuelMeraz, I am not sure using blt_add_test really buys you much here - 
I would just stick to using the basic add_test, or maybe go with your own macro if you need to customize the python env. 

Here is a semi complex example:
https://github.com/LLNL/conduit/blob/master/src/cmake/SetupTests.cmake

**Comment by ManuelMeraz** [comment]
@cyrush Yeah I was thinking of writing my own macro, but for now like you said, I'm currently sticking with the vanilla add_test. Appreciate the help :).

**Comment by DavidPoliakoff** [comment]
Hey guys, if everybody's happy with the "just use add_test" solution, that's good enough for me. I'll close it, feel free to reopen if it becomes interesting again
