### ISSUE TITLE
Incorrect variable used to determine if CUDA runtime is used

### ISSUE THREAD

**Issue by BurlMHall** [LLNL/blt#221]
On line 235 of BLTPrivateMacros.cmake, _cuda_index is used instead of _cuda_runtime_index.  Because of this, executables which depend on cuda_runtime are not properly flagged to link with CUDA when CUDA_LINK_WITH_NVCC is set.

   list(FIND arg_DEPENDS_ON "cuda_runtime" _cuda_runtime_index)
     set(_depends_on_cuda_runtime FALSE)
     if(${_cuda_index} GREATER -1)
         set(_depends_on_cuda_runtime TRUE)
     endif()

This bug is blocking the 8.2 LEOS release.

**Comment by cyrush** [comment]
@BurlMHall - seems like there is a simple fix, do you mind creating a pull request? I think you are in the best position to test + validate the change.

**Comment by BurlMHall** [comment]
Hi Cyrus,

I’ve created the pull request.

Burl

Burl M. Hall
Applications, Simulations, and Quality Division
L-098
Lawrence Livermore National Laboratory
Livermore, CA 94551
925-424-6200         hall53@llnl.gov

**Comment by cyrush** [comment]
resolved in PR #222
