### ISSUE TITLE
Should use target property?

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/blt#239]
https://github.com/LLNL/blt/blob/07d3e3cc8613e05af0a6a75ac0d0a70cb91ebc30/docs/tutorial/calc_pi/CMakeLists.txt#L22

I am passing a long a comment to BLT code I copied into my project from a CMake expert @bartlettroscoe and ontributor to Sandia's TRIBITS CMake infrastructure.

The above referenced line should use target property instead

**Comment by cyrush** [comment]
the blt macros now handle this. 

I am also surprised that example still needs that flag. We may be able to just take it out.

**Comment by kennyweiss** [comment]
Thanks @markcmiller86  and @bartlettroscoe

We also do the same thing here:
https://github.com/LLNL/blt/blob/07d3e3cc8613e05af0a6a75ac0d0a70cb91ebc30/tests/internal/CMakeLists.txt#L24-L26

I agree that target properties would be better and we should make the switch. 
As @cyrush mentioned, we should also check that they are still needed.
