### ISSUE TITLE
new cmake object library support (OpenMP)

### ISSUE THREAD

**Issue by mclarsen** [LLNL/blt#240]
I ran into a couple issues with  the object library support with newer versions of CMake (3.12+).

Issue is that the object library depends on OpenMP. In the `old_object_library_support` everything works fine, but in newer versions of cmake, the code hits:

https://github.com/LLNL/blt/blob/07d3e3cc8613e05af0a6a75ac0d0a70cb91ebc30/cmake/BLTPrivateMacros.cmake#L177

Since OpenMP is not a target, it should skip this, otherwise I end up with a `-lopenmp` that errors on linking.

**Comment by white238** [comment]
Is this fixed in the new BLT?

**Comment by mclarsen** [comment]
I just tried this again with CMake 3.12.1 and the latest commit, but the issue now seems to be the the c++11 flags are not being passed to the object lib so it never gets to linking.

**Comment by mclarsen** [comment]
After manually adding `set (CMAKE_CXX_STANDARD 11)` to the CMakeLists file, it compiles and links.

**Comment by davidbeckingsale** [comment]
@mclarsen - are you explicitly setting `BLT_CXX_STD`?  #243 was merged recently which leaves it undefined by default.

**Comment by white238** [comment]
Spoke with @mclarsen and this issue has been resolved.
