### ISSUE TITLE
Docs examples don't include the correct cmake lines

### ISSUE THREAD

**Issue by mcneish1** [LLNL/blt#262]
On https://llnl-blt.readthedocs.io/en/latest/creating_execs_and_libs.html, all the code boxes but the last are various shades of wrong.

The first probably should point to lines 21-25, the second should fully bracket `<BLT repository>`, and the third probably should point to lines 27-32.

https://llnl-blt.readthedocs.io/en/latest/unit_testing.html and https://llnl-blt.readthedocs.io/en/latest/external_dependencies.html look like they have the same issues, but the rest of the docs look fine.

**Comment by white238** [comment]
Thank you. I'll take a look at this soon and update it to the better/more robust start-after/end-before sphinx feature that doesn't cause so many problems like line numbers does.
