### ISSUE TITLE
Increase number of ranks in mpi smoke test

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#263]
Our ``blt_mpi_smoke`` test is currently configured to run with 2 ranks.

One of our user codes experienced a regression when this test is run with 4 or more ranks with certain platform/compiler/mpi combinations.

Specifically, LLNL's `toss3` platform with `clang` compilers on `mvapich2-2.2` after a recent update to mpi.

**Comment by cyrush** [comment]
I am confused, why are they trying to run the built in test with more than 2 ranks?

**Comment by cyrush** [comment]
Looked at more details - Ok, that is strange.

Not sure we need to increase the number of ranks to catch this weird case.

That said we do expect basic MPI issues to be identified here.

**Comment by kennyweiss** [comment]
@cyrush -- I increased the number of ranks for `blt_mpi_smoke` while diagnosing an mpi-related problem, where `blt_mpi_smoke` with 2 ranks was passing, but almost all the other mpi-related tests were failing.

Increasing this test to 4 seems like a pretty easy way to catch more mpi-related problems, and somehow 2 ranks weren't sufficient for this regression.

**Comment by cyrush** [comment]
@kennyweiss  strange but good insurance, so sounds good.
Sorry for the noise.
