### ISSUE TITLE
CUDA static linking  question with separable compilation and nvcc linking

### ISSUE THREAD

**Issue by mclarsen** [LLNL/blt#270]
So I this situation:
gcc 5.4.0, blt master, and cmake 3.9.2

unit_test (no cuda code) -> lib_a.a (no cuda code) -> lib_b.a (yes cuda code requires sep comp and nvcc linking)

The unit tests fail to link because gcc has no idea where `__cudaRegisterLinkedBinary` is.

 If I turn on separable compilation and nvcc linking (adding cuda as a dep), the unit test in the example fail because `nvcc fatal   : Unknown option `Wl,-rpath,/some_path_to_zlib_that_spack_built`.

Any ideas?

**Comment by cyrush** [comment]
just to check: no mfem in this case?

**Comment by mclarsen** [comment]
Yes, no mfem.

**Comment by mclarsen** [comment]
Here is a simpler example. Separable compilation and linking with cuda is on. All gtest are failing to build since nvcc does not know about pthreads. 

`nvcc fatal   : Unknown option 'pthread'`

**Comment by mclarsen** [comment]
After some recent discoveries, this is a cmake failure. Only versions of cmake 3.13.1+ do the right thing here.
