### ISSUE TITLE
Support for non-standard hwloc installation

### ISSUE THREAD

**Issue by pjh40** [LLNL/blt#296]
I'm working on a platform that does not have a system-installed hwloc, which causes build problems with the blt_cuda_mpi_smoke tests in rev 9383457.  I've worked around this by adjusting CXXFLAGS and LDFLAGS, but it would be nice to have a find hwloc capability (unless it is there and I'm just missing it).

**Comment by white238** [comment]
This is no longer a requirement of the smoke test and is now an internal test.  It's probably not worth fixing for the internal tests since only BLT developers run them.
