### ISSUE TITLE
C++11 support needed for blt_cuda_mpi_smoke

### ISSUE THREAD

**Issue by pjh40** [LLNL/blt#297]
I'm running into trouble when trying to build the `blt_cuda_mpi_smoke` (rev 9383457) test, but I'm not sure if this is a blt issue or a local configuration problem, and I was looking for some advice.

The platform is Power9+Tesla, running
```
Linux 4.14.0-115.7.1.el7a.ppc64le #1 SMP Thu Mar 28 16:03:17 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
```
and compiling with XL-16.1.1.3, CUDA 10.1, and OpenMPI 4.0.1.

If I attempt to compile a BLT project with this configuration, I get while compiling `blt_cuda_mpi_smoke.cpp` during the include of `<cstdint>` about it needing C++11 support:
```
In file included from /home/phenning/Projects/UTA-Proj/UTA/blt/tests/smoke/blt_cuda_mpi_smoke.cpp:42:
In file included from /projects/opt/ppc64le/gcc/4.9.3/lib/gcc/powerpc64le-unknown-linux-gnu/4.9.3/../../../../include/c++/4.9.3/cstdint:35:
/projects/opt/ppc64le/gcc/4.9.3/lib/gcc/powerpc64le-unknown-linux-gnu/4.9.3/../../../../include/c++/4.9.3/bits/c++0x_warning.h:32:2: error: 
      This file requires compiler and library support for the ISO C++ 2011
      standard. This support is currently experimental, and must be enabled with
      the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support for the \
 ^
make[2]: *** [blt/tests/smoke/CMakeFiles/blt_cuda_mpi_smoke.dir/blt_cuda_mpi_smoke.cpp.o] Error 1
```
This is weird to me for several reasons that make me suspect local XL configuration problems.  First is that I thought `<cstdint>` (for the most part) was available pre-C++11. And second, I don't know why XL is looking up such an old gcc version. However, I find that adding a `set(BLT_CXX_STD "c++11" ...` command fixes this, so I don't know if this is something peculiar to the XL family of compilers that should be handled in BLT.  Thoughts?

**Comment by cyrush** [comment]
thats a fun one, not sure how critical any use of cstdint functionally is -- given the compiler isn't happy, maybe we should refactor to avoid using it. This test is actually quite a bit more complex than I would suggest for a smoke test.

**Comment by trudeaun** [comment]
`<cstdint>` was made available with C++11 support in XL and GCC. With XL, and you can enable C++11 support with `-std=c++11`. To point XL to a newer version of GCC, please read [Configuring IBM XL C/C++ for Linux, V16.1.1](https://www.ibm.com/support/knowledgecenter/SSXVZZ_16.1.1/com.ibm.xlcpp1611.lelinux.doc/install/configcompiler.html?sc=SSXVZZ_latest) on Knowledge Center.

**Comment by white238** [comment]
I will refactor this smoke test to be much simpler hopefully today.
