### ISSUE TITLE
Compile definitions all public

### ISSUE THREAD

**Issue by mclarsen** [LLNL/blt#307]
Compile definitions added to a target through BLT are all public and are propagated to all downstream deps. Is this a design decision or would it be appropriate to add a flag for `PUBLIC' versus`PRIVATE`?

I note that all of our compile definitions do not need to be propagated, and in one case should not be propagated.

**Comment by white238** [comment]
@mclarsen does #311 solve your problem?

**Comment by mclarsen** [comment]
@white238 Yes, that would solve my problem.
