### ISSUE TITLE
Turn off smoke tests?

### ISSUE THREAD

**Issue by junkudo** [LLNL/blt#310]
Hey,
I'd like to be able to turn off specific (or all) smoke tests if possible.  Is this possible without modifying BLT itself? The `blt_mpi_smoke` invokes slurm and I'd like to avoid the wait time associated with that if possible.  I guess I can always filter it out manually.

**Comment by kennyweiss** [comment]
Thanks for the suggestion @junkudo.  

We added those tests to allow people building their codes to quickly determine if ``gtest``, ``mpi``, ``openmp``, ``cuda``, etc. were configured correctly.  We've found this to be extremely helpful in debugging build issues, especially on non-standard platforms like bgq and blueos, and I'd recommend that you consider leaving them enabled.

On the other hand, I suppose we could add an advanced option, e.g. ``BLT_ENABLE_BUILTIN_SMOKE_TESTS``, with a default of ``ON`` to allow users to disable blt's built-in tests. (In the spirit of keeping things simple, I don't think we'd want to allow users to toggle individual smoke tests).

Thoughts? @white238, @cyrush, or others.

**Comment by white238** [comment]
This has come up before and we have always come down on the side of leaving them always enabled.  The whole purpose of those tests are to show you when something has gone horribly wrong in your configuration and not in the users tests.

These tests are intentionally very small and quick.  I haven't found a system that these cause more then a millisecond added to the whole test run.  Not knowing anything about @junkudo's system, I would question how much wait time these could be adding.  Is there a possibly better batch command it could be using or possibly running them all in one batch?

**Comment by junkudo** [comment]
Thanks for the quick reply!

My problem is that it's invoking slurm (`Test command: /usr/bin/srun "-n" "2" "blt_mpi_smoke"`) using whatever the default queue is, and waits for the resource allocation. In my case on Quartz, this happens to be the batch queue which is relatively over-subscribed so it tends to spin for a while.

**Comment by kennyweiss** [comment]
Thanks for the context @junkudo.  

Since we can't build on login nodes either, I typically grab an allocation for my build (e.g. using ``salloc -N1 --exclusive`` on ``toss3``), and use this to run the tests as well.

Does your application have other mpi-based unit tests?

It looks like you can explicitly disable a test from your code's build system. e.g. using something like the following:
```cmake
set_tests_property(blt_mpi_smoke PROPERTIES DISABLED TRUE)
```
See: 
* https://cmake.org/cmake/help/latest/command/set_tests_properties.html?highlight=s
* https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#properties-on-tests
* https://cmake.org/cmake/help/latest/prop_test/DISABLED.html

**Comment by white238** [comment]
If you have other MPI tests in your test suite you should be running with either a "srun" around your whole make test.  This will stop it from asking for an individual resource for each test.  You can do that a few ways.

like so:

srun -N1 make test

This will run in pdebug (which to call it oversubscribed is an understatement) and has a overall limit of 30 minutes (according to my LC Coordinator). 

Or you can run it as a batch job and control the bank and time limit.  Here is an example:

#!/usr/bin/bash
 
## run this by coping it into a file, then typing "sbatch <nameOfTheFile>
#SBATCH --job-name=BANANA
#SBATCH --qos=normal
#SBATCH --account=cbronze
#SBATCH --time=1:00:00
#SBATCH --partition=pbatch
#SBATCH --nodes=1
  
make test

**Comment by junkudo** [comment]
Thanks - these are all helpful suggestions!

**Comment by junkudo** [comment]
@kennyweiss I'm satisfied with the answers provided here but I just wanted to let you know that I couldn't actually disable the test manually.
I got the error message:
```bash
 set_tests_properties Can not find test to add properties to: blt_mpi_smoke
```
whenever I tried to disable the test.  If I put the disable command where the test is created, it works.  It seems like CMake tests are locally scoped as it seems like I'm unable to modify the properties of tests created in subdirectories from the parent scope.

**Comment by kennyweiss** [comment]
Thanks for the update @junkudo.

> It seems like CMake tests are locally scoped as it seems like I'm unable to modify the properties of tests created in subdirectories from the parent scope.

That's unfortunate, but good to know. 
@white238 -- do you think we could create a BLT macro to work around this?
