### ISSUE TITLE
Output when ENABLE_CLANGQUERY is unset

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/blt#318]
Hey folks,

I happened to spot [this bug](https://github.com/LLNL/RAJA/issues/684#issuecomment-551333211) on the RAJA issue tracker, in which somebody links some output they get from configuring RAJA

```
-- HIP Support is OFF
-- HCC Support is OFF
-- Sphinx support is ON
-- Valgrind support is ON
-- Uncrustify support is ON
-- Failed to locate Uncrustify executable (missing: UNCRUSTIFY_EXECUTABLE) 
-- AStyle support is ON
-- Failed to locate AStyle executable (missing: ASTYLE_EXECUTABLE) 
-- Cppcheck support is ON
-- Failed to locate Cppcheck executable (missing: CPPCHECK_EXECUTABLE) 
-- ClangQuery support is 
-- C Compiler family is Clang
```

If you look, unlike AStle or Uncrustify or Valgrind, ClangQuery support is not "ON" or "OFF", we just get "ClangQuery support _is_". Knowing who implemented the clang-query support, I'm 99% sure it's that person's fault. Any tips on how said person might fix this?

**Comment by white238** [comment]
Thanks for pointing this out @DavidPoliakoff ! I have a PR with a fix that will go through on develop soon.

**Comment by DavidPoliakoff** [comment]
Thanks Chris. I like your odds on getting that PR through, I'll close this issue
