### ISSUE TITLE
Any work already or interest in adding gitlab-ci support

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/blt#321]
I am just learning about gitlab-ci and, in particular, ECP-CI resources which are all being enabled via gitlab servers and gitlab-ci services.

I am wondering if BLT project is already making progress or would be interested in working with me to add gitlab-ci support, and, in particular, demonstrating calc-pi and other tests running across ECP-CI complex?

**Comment by cyrush** [comment]
@markcmiller86 that would be great, however I am not sure what the status of the ECP-CI is right now? There may be constraints about who can commit? 

I think we have some internal testing setup for blt inside LLNL.

**Comment by markcmiller86** [comment]
> however I am not sure what the status of the ECP-CI is right now?

I am working regularly with that team helping to develop examples and documentation. I hope to be helping them with the ECP-CI tutorial at ECP meeting.

What I am thinking for BLT is to have calc-pi and other examples working in gitlab ci, first locally at LLNL and then across ECP-CI resources.

**Comment by white238** [comment]
Fixed in #457
