### ISSUE TITLE
cuda vs pthread again

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#390]
```
[  1%] Linking CXX executable ../../../tests/blt_mpi_smoke
cd /ccs/home/cyrush/2020.08.ascent/build_test/blt/tests/smoke && /gpfs/alpine/csc340/world-shared/software/ascent/2020-08-13/summit/cuda/gnu/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/cmake-3.14.5-uk6fhxv4tu3svs5zh4lwupit7pn4z42e/bin/cmake -E cmake_link_script CMakeFiles/blt_mpi_smoke.dir/link.txt --verbose=1
/sw/summit/gcc/6.4.0/bin/g++      -O3 -DNDEBUG  SHELL:-pthread CMakeFiles/blt_mpi_smoke.dir/blt_mpi_smoke.cpp.o  -o ../../../tests/blt_mpi_smoke /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib/libmpiprofilesupport.so /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib/libmpi_ibm.so -lmpi_ibm_usempi /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib/libmpi_ibm_mpifh.so 
g++: error: SHELL:-pthread: No such file or directory
```

**Comment by white238** [comment]
random thought: "SHELL:" probably needs to be guarded against CMake version <3.13

**Comment by cyrush** [comment]
not sure why `SHELL:` survives in this case, but since `pthread` is a magical  compiler thingy, it probably demands magic.

**Comment by cyrush** [comment]
this is: cmake version 3.14.5

**Comment by cyrush** [comment]
this happens when we re-configure, fine on first config

**Comment by white238** [comment]
re-configuring should be banned... its never reproducable imo.

**Comment by cyrush** [comment]
agreed, but I am worried it's easy to trigger this -- Might happen if you edit a CMakeLists.txt file (vs play with ccmake)

**Comment by cyrush** [comment]
`g++: error: SHELL:SHELL:SHELL:SHELL:SHELL:SHELL:SHELL:SHELL:-pthread: No such file or directory`

**Comment by cyrush** [comment]
i think this could be my bad, but I am a bit confused. It looks like we clear everything to start with a blank slate for the MPI flags, but some how -- thats not the case

**Comment by white238** [comment]
> `g++: error: SHELL:SHELL:SHELL:SHELL:SHELL:SHELL:SHELL:SHELL:-pthread: No such file or directory`

SuperShell to the rescue!

**Comment by rcarson3** [comment]
Don't know if this is related, but I've also run into issues compiling my code ExaConstit on Summit where this pthread issue pops up again for CUDA builds and gtest. Their versions of cmake/3.17.3 and cmake/3.18.1 are causing issues there when building with blt v0.3.0. 

Although, it does work with blt v0.3.6 on cmake/3.18.1 but not the most recent commit according to one of the CI guys on my team.

I will say though that things do appear to build correctly on rzansel with cmake/3.18.0 and blt v0.3.0, so it very well could be something off with their version of cmake which appears to be built using spack.
