### ISSUE TITLE
Add macros for basic git commands in BLT

### ISSUE THREAD

**Issue by gzagaris** [LLNL/blt#4]
BLT should provide a few cmake functions or macros to glean basic git information. For example, a Git the tag of a branch and/or the SHA1 at the tip of a branch.

The motivation for this is to provide the means for BLT-based projects to configure header files that consist of the Project's version, e.g., something like a "Version.h", or "configure.h"

For example, potential things client code would want to do include the following:
```
## gets the tag from the given branch, i.e., with git --describe
blt_git_tag( BRANCH <BRANCH> SOURCE_DIR <SOURCE_DIR> )
```

```
## gets the SHA1 hash at the tip of the given branch
blt_git_hash( BRANCH <BRANCH> SOURCE_DIR <SOURCE_DIR>  )
```

```
## get the name of the branch that is checked out
blt_git_branch( SOURCE_DIR <SOURCE_DIR> )
```

**Comment by rhornung67** [comment]
:+1:

**Comment by gonsie** [comment]
There is a module from [@rpavlik/cmake-modules](https://github.com/rpavlik/cmake-modules) that may be a good reference for this functionality. I've used it before to get the git-hash for the current version of a code base.

The module consists of 2 files: [GetGitRevisionDescription.cmake](https://github.com/rpavlik/cmake-modules/blob/master/GetGitRevisionDescription.cmake) and [GetGitRevisionDescription.cmake.in](https://github.com/rpavlik/cmake-modules/blob/master/GetGitRevisionDescription.cmake.in)

**Comment by gzagaris** [comment]
@gonsie yes, I've seen that. I was thinking of something along those lines
