### ISSUE TITLE
Remove hard-coded C++11 in CUDA flags

### ISSUE THREAD

**Issue by white238** [LLNL/blt#403]
https://github.com/LLNL/blt/blob/develop/cmake/thirdparty/SetupCUDA.cmake#L85

**Comment by adayton1** [comment]
If it's a simple matter of replacing that hardcoded flag with a cmake variable, I could put in a merge request. Is there a BLT_CUDA_STD variable?

**Comment by white238** [comment]
Related logic here:

https://github.com/LLNL/blt/blob/e35f490a8a8b1689e99b5f4308b5251f97eb36cf/cmake/SetupCompilerOptions.cmake#L168-L179

And defining std flags here:

https://github.com/LLNL/blt/blob/e35f490a8a8b1689e99b5f4308b5251f97eb36cf/cmake/SetupCompilerOptions.cmake#L259-L322

**Comment by white238** [comment]
I think that should work.  Not all compilers use the standardized flag but NVCC uses the normal flags like BLT accepts.  Is there a case where you wouldn't want them to be the same? Like C++17 for everything but the CUDA specific code...  I'm probably over thinking this and we can solve this later if it comes up.

**Comment by white238** [comment]
Fixed in #570
