### ISSUE TITLE
Failing LLNL blues_os PGI host-config

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#439]
The following LLNL host-configs has been failing for the past few weeks:
https://github.com/LLNL/blt/blob/develop/host-configs/llnl/blueos_3_ppc64le_ib_p9/pgi%4020.4_nvcc.cmake

When attempting to build our internal tests
```bash
>cmake -C ../host-configs/llnl/blueos_3_ppc64le_ib_p9/pgi@20.4_nvcc.cmake ../tests/internal/
```

I got the following error messages:
```make
pgc++-Error-Unknown switch: -isystem
make[2]: *** [blt/tests/smoke/CMakeFiles/blt_cuda_smoke.dir/build.make:63: blt/tests/smoke/CMakeFiles/blt_cuda_smoke.dir/blt_cuda_smoke.cpp.o] Error 1
make[2]: *** [src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_lib.dir/build.make:76: src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_lib.dir/Parent.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1616: blt/tests/smoke/CMakeFiles/blt_cuda_smoke.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

pgc++-Error-Unknown switch: -isystem
make[2]: *** [src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_lib.dir/build.make:63: src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_lib.dir/Child.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2046: src/test_cuda_device_call_from_kernel/CMakeFiles/t_cuda_device_call_from_kernel_lib.dir/all] Error 2

pgc++-Error-Unknown switch: -isystem
make[2]: *** [calc_pi/CMakeFiles/calc_pi_cuda.dir/build.make:63: calc_pi/CMakeFiles/calc_pi_cuda.dir/calc_pi_cuda.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2589: calc_pi/CMakeFiles/calc_pi_cuda.dir/all] Error 2

...

[ 28%] Linking CXX static library ../lib/libcalc_pi.a
[ 28%] Built target example
"/usr/tce/packages/cuda/cuda-10.1.243/include/crt/host_defines.h", line 54:
          warning: unrecognized preprocessing directive
  #warning "crt/host_defines.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
   ^
```

**Comment by kennyweiss** [comment]
I suspect it has to do with the special treatment of `*_TREAT_INCLUDES_AS_SYSTEM` for PGI
and the difference between the treatment of this flag with `blt_register_library` vs. `blt_import_library`.

See:
https://github.com/LLNL/blt/blob/a98a5836c7a9e34b75a54eb46212812796fe5557/cmake/BLTMacros.cmake#L363-L369
and/or
https://github.com/LLNL/blt/blob/a98a5836c7a9e34b75a54eb46212812796fe5557/cmake/BLTMacros.cmake#L482-L494

**Comment by kennyweiss** [comment]
The issue appears to be that for `IMPORTED` targets, `INTERFACE_INCLUDE_DIRECTORIES` are marked as `SYSTEM` by default, but PGI does not support `SYSTEM` targets. 
See: https://cmake.org/cmake/help/latest/prop_tgt/NO_SYSTEM_FROM_IMPORTED.html#prop_tgt:NO_SYSTEM_FROM_IMPORTED

CMake is labeling our `blt_import_library` targets as SYSTEM (and generating `isystem` instead of `-I` for these includes. This might be a bug in their handling of IMPORT targets for PGI. 

As I suspected, this was triggered when we converted our `blt_register_library` targets to `blt_import_library` targets in #421

**Comment by white238** [comment]
> The issue appears to be that for `IMPORTED` targets, `INTERFACE_INCLUDE_DIRECTORIES` are marked as `SYSTEM` by default, but PGI does not support `SYSTEM` targets.
 

That's "helpful".
