### ISSUE TITLE
Header-only libraries DEPENDS_ON support

### ISSUE THREAD

**Issue by white238** [LLNL/blt#44]
The call of blt_setup_target inside blt_add_library for header-only libraries needs to be reworked.  You can only add INTERFACE dependencies to header-only libraries.  Otherwise you get the following error:

CMake Error at blt/cmake/BLTPrivateMacros.cmake:155 (target_link_libraries):
  INTERFACE library can only be used with the INTERFACE keyword of
  target_link_libraries
Call Stack (most recent call first):
  blt/cmake/BLTMacros.cmake:433 (blt_setup_target)
  components/primal/src/CMakeLists.txt:39 (blt_add_library)

**Comment by davidbeckingsale** [comment]
I've seen this before. It's a pain in the butt.

**Comment by cyrush** [comment]
@white238, I think you fought the battles to resolve this?

**Comment by white238** [comment]
current work around until I can come up with a better solution is to do the following:

blt_add_library(NAME my_header_only_library
                         HEADERS foo.hpp)
target_link_library(my_header_only_library INTERFACE my_dependency_library)

**Comment by twang15** [comment]
I have installed raja under pathA.
Is there an example to show how a project can use it in blt?

**Comment by twang15** [comment]
Thanks for sharing this code. It seems to build raja within my current
project.

In my case,
Raja is aldready built and installed.
I just want to import it to a project which needs to link to raja.

**Comment by davidbeckingsale** [comment]
In that case, you can just use the `blt_register_library` part of the example, but call `find_package(RAJA)` before. See here: https://raja.readthedocs.io/en/release-0.6.0rc3/using_raja.html

**Comment by gzagaris** [comment]
Oh, I misunderstood your question. In that case, I think you can just do the last `blt_register_library` step pointing it to the Raja includes folder and library.

**Comment by white238** [comment]
This was fixed at some point.
