### ISSUE TITLE
Add FRUIT MPI extensions for MPI-aware Fortran unit tests?

### ISSUE THREAD

**Issue by goxberry** [LLNL/blt#444]
Would there be any interest if I filed a PR adding the `fruit_mpi.f90` source file from FRUIT 3.4.1, plus a smoke test? I use FRUIT's MPI extensions in unit tests of a modal analysis package I'm developing for some of the lab's legacy codes. I'd like to update the build system so it uses BLT's copy of FRUIT, but I need those MPI extensions in order to run those tests.

**Comment by white238** [comment]
That sounds very useful.  Without looking into it, will adding it cause any conflicts with existing non-mpi fruit tests?

**Comment by goxberry** [comment]
I haven't seen any conflicts between `fruit` and `fruit_mpi` when I've used them; `fruit_mpi` is a separate module that adds some reporter procedures on top of the core `fruit` API. See https://github.com/LLNL/blt/pull/446/files#diff-35bc1dbf726692f994b8d0c74f79bd259907e6b89b6ccf24b4151e1e96402c37 for example usage.

**Comment by goxberry** [comment]
I wrote a single-header-only plugin for Google Test that does a similar sort of pretty-printing/summary reporting thing for gtest and C++. I wrote most of it 3 years ago, rather hastily -- if it's of interest, I could iterate with the BLT team to clean it up because it could definitely be improved. The plugin has already gone through review and release.

https://github.com/LLNL/gtest-mpi-listener
