### ISSUE TITLE
Warnings when using blt in cmake projects that use a new style project command

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#46]
When you add a project using this style of `project` command:

project(project_name VERSION "x.y.z") 

Our google test and google mock sub projects trigger the following warnings

```
CMake Warning (dev) at blt/thirdparty_builtin/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by davidbeckingsale** [comment]
We can update the project commands in those files, but would that complain when people use the old style `project` command?

**Comment by cyrush** [comment]
Thankfully, it turns out there is a simple fix:

https://github.com/google/googletest/pull/782/files

(this PR hasn't been pulled into google test yet)

I was trying to add the policy commands in the wrong places (I missed the top level project)
