### ISSUE TITLE
regex match of clang-format --version output hanging

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/blt#499]
on rznevada, some users noticed their cmake process hanging. I was able to track this down to the regex match in https://github.com/LLNL/blt/blob/develop/cmake/SetupCodeChecks.cmake trying to parse the output of `clang-format --version`. I think the issue is that the Cray version of clang-format adds some unexpected strings. Compare the vanilla output:

[lee218@rzgenie2:build]$ /usr/tce/packages/clang/clang-11.0.1/bin/clang-format --version
clang-format version 11.0.1

versus the Cray version on rznevada:

[lee218@rznevada15:build]$ /opt/cray/pe/cce/12.0.0/cce-clang/x86_64/bin/clang-format --version
Cray clang-format version 12.0.0  (59041842ced75ac192c0f1331989ae45f58d7caf)

Would it be possible to modify the regex match to properly parse this output?

**Comment by kennyweiss** [comment]
Thanks for looking into this @lee218llnl 

Looks like the issue is here:
https://github.com/LLNL/blt/blob/9e4931c3c6d6635de0b216cfc998d28dfa7ba5dd/cmake/SetupCodeChecks.cmake#L681-L698

**Comment by white238** [comment]
Is there a known case that the much simpler regex `(\d+\.\d+\.?\d?)` does not match?
