### ISSUE TITLE
Cannot recognize the extension when compiling with xxx.xxx.c file

### ISSUE THREAD

**Issue by ctian282** [LLNL/blt#515]
When compiling with some old C projects, source files with names like 1d.cube.order2.c cannot be recognized as C file. Error message 

```
CMake Error at blt/cmake/BLTPrivateMacros.cmake:822 (message):
  blt_split_source_list_by_language given source file with unknown file
  extension.  Add the missing extension to the corresponding list
  (BLT_C_FILE_EXTS, BLT_Fortran_FILE_EXTS, BLT_Python_FILE_EXTS, or
  BLT_CMAKE_FILE_EXTS).

   Unknown file: xxx/1d.cube.order2.c
Call Stack (most recent call first):
  blt/cmake/BLTPrivateMacros.cmake:547 (blt_split_source_list_by_language)
  blt/cmake/BLTMacros.cmake:787 (blt_setup_cuda_target)
  CMakeLists.txt:109 (blt_add_executable)
```

will show up. Is there easy way to fix this?

**Comment by goxberry** [comment]
`blt_split_source_list` will use the CMake macro [`get_filename_component`](https://cmake.org/cmake/help/latest/command/get_filename_component.html) to split the file's basename on the first period (from left-to-right) to determine the file's extension. In your example, BLT parses the extension as `.cube.order2.c`.

Once BLT determines the file's extension, BLT looks for that extensions within the list of extensions stored in `BLT_C_FILE_EXTS`. To get BLT to recognize that file as a C file, you would need to add
```cmake
list(APPEND BLT_C_FILE_EXTS ".cube.order2.c")
```
before you call the `blt_add_code_checks` macro in CMake. You'll have to add such extensions for each C file with an extension not in the list [here](https://github.com/LLNL/blt/blob/5bff638521161c9932e679f493efe366369a3f74/SetupBLT.cmake#L175) for BLT to recognize it as a C file in code checks.

**Comment by kennyweiss** [comment]
Thanks for reporting this issue @ctian282 and for digging into the issue @goxberry.

It looks like the larger issue might be that BLT is finding an extension with too many terms. 
Perhaps we should instead attempt to only capture the last part of the extension (e.g. `.c` in this case)

Thoughts @white238 ?

**Comment by white238** [comment]
I see two options for changing how `blt_split_source_list` works:

- use  `LAST_EXT` instead of `EXT` in `get_filename_component`
- do a regex test for the file path ends with the extention

Thoughts?

**Comment by goxberry** [comment]
`LAST_EXT` requires CMake 3.14 or later, but it’s simplest. Stripping the period and iteratively applying `get_filename_component` could also work — if `get_filename_component(… EXT)` returns nothing, then the iteration terminates.

**Comment by goxberry** [comment]
A one-shot regex would probably be more efficient.

**Comment by goxberry** [comment]
@white238 @white238 I think a regex generated by something like this function should work?

```cmake
function(blt_make_regex_from_ext_list ext_list ext_regex)
    set(joined_ext_list “”)
    if(CMAKE_VERSION VERSION_GREATER_EQUAL “3.12”)
        list(JOIN “|” joined_ext_list ext_list)
    else()
        foreach(extension ext_list)
            string(APPEND joined_ext_list “${extension}|”)
        endforeach()
        string(REGEX REPLACE “^(.*)|$” “\\1” joined_ext_list “${joined_ext_list}”)
    endif()

    string(REPLACE “.” “\.” escaped_joined_list “${joined_ext_list}”)
    set(${ext_regex} “^.*(${escaped_joined_list})$” PARENT_SCOPE)
endfunction()
```

I think the regex needs to look something like, e.g., `^.*(\.c|\.cpp|\.cc|\.C)$`, except obviously the collection of extensions at the end needs to be built up from lists like `BLT_C_FILE_EXTS`. Once the regex-generating function is added, the `blt_split_source_list_by_language` macro in `blt/cmake/BLTPrivateMacros.cmake` needs to use `if(… MATCHES …)` instead of `if(… IN_LIST …)` for extension testing.

I’ll try to PR this change, plus some docs, over the weekend. Is there any unit testing of functions in CMake, or any tests I should add for this sort of change?

**Comment by kennyweiss** [comment]
Thanks @goxberry 

Our internal tests are in `<blt>/tests/internal`, and can tested by configuring a build with a host-config that points to this directory.

This should be documented, but in case it's not, something like the following should work:
```bash
> git clone blt
> cd blt
> mkdir build-blt && cd build-blt
> cmake -C ../host-configs/<desired-host-config> ../tests/internal
> make -j
> ctest -j
```
