### ISSUE TITLE
Make `HIP_HIPCC_FLAGS` into a generator expression

### ISSUE THREAD

**Issue by white238** [LLNL/blt#524]
Do you know if we can make this a generator? Both Fortran and C that use HIP runtime (even indirectly) need to b e linked with hipcc, and then this breaks things. cc @trws

_Originally posted by @davidbeckingsale in https://github.com/LLNL/blt/pull/523#discussion_r710378363_

**Comment by davidbeckingsale** [comment]
Generator doesn't work, I just tried it 😢

**Comment by trws** [comment]
Interesting, the FindHIP stuff seems to use a hipcc linker helper thing for that, and those have all their own variables.  Maybe there's a way we can get it to apply only to the compilation rather than the link, let me take a look.

**Comment by trws** [comment]
Is there an example of something like that I can easily grab? I'm trying to figure out how we end up with the HIPCC flags in a link, they shouldn't apply through the FindHIP stuff, so I need to track down how they get in there.

**Comment by davidbeckingsale** [comment]
Yes, let me send you a message

**Comment by davidbeckingsale** [comment]
Turns out this was a mistake on my end, sorry for the noise.
