### ISSUE TITLE
hip_smoke_tests broken with cmake@3.21

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#536]
When testing blt using our internal tests, I discovered that the `hip_smoke_test` is broken with `cmake@3.21.1`

Reproducer:
```
# Run from a fresh clone of blt on the develop branch on 10/28/2021
> ml cmake@3.21.1
> mkdir build-debug && cd build-debug
> cmake -C ../host-configs/llnl/toss_4_x86_64_ib_cray/cce@12.0.0_clang_hip.cmake ../tests/internal/
> make
>ctest -R blt_hip_smoke -VV

test 11
    Start 11: blt_hip_smoke

11: Test command: <blt>/build-debug/tests/blt_hip_smoke
11: Test timeout computed to be: 1500
11: "hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
1/1 Test #11: blt_hip_smoke ....................Subprocess aborted***Exception:   0.93 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.97 sec

The following tests FAILED:
	 11 - blt_hip_smoke (Subprocess aborted)
```

Note: This issue will likely be superseded by #526

**Comment by trws** [comment]
Is this specifically with CCE or with rocm as well?

**Comment by kennyweiss** [comment]
@trws -- I'm not entirely sure -- I only tried with the host-config that was available.
As mentioned in #534, we should add a working host-config for `rocm`.

I resolved the problem by updating to the newer compiler drop, and didn't dig too much deeper since #526 is swapping out most of the hip setup.

**Comment by trws** [comment]
That makes sense, I asked mainly because I tested actively with 3.21 against amd-clang and hipcc both, but not with cce, so that would be an easy place for a bug to have eluded me on the HIP tweaks.
________________________________

**Comment by kennyweiss** [comment]
Seems like it is just a CCE thing.

I created a `rocm+hip` host-config in #538 and successfully tested it against `cmake@3.19` and `cmake@3.21`
