### ISSUE TITLE
blt_gmock_smoke crashes with gcc 4.9.3 on surface

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#55]
It's crashing when cleaning up global objects:

`6  0x00002aaaab1f1713 in __do_global_dtors_aux () from build-debug/lib/libgmock_main.so`

this may be an issue with our smoke test, or an issue with gmock

Here are some (likely) related threads:

- https://groups.google.com/forum/#!topic/googlemock/5W-zJKZFtE0
- (this issue is refed from above thread: https://github.com/google/googlemock/issues/54)
- https://github.com/google/googletest/issues/461

**Comment by cyrush** [comment]
Our example doesn't include  any global instances of objects, so I think this probably bad luck with global destruction of something in gmock.

**Comment by white238** [comment]
GMock has been updated multiple times since then.  If this didn't get fixed then someone will create a new issue.
