### ISSUE TITLE
Create macro to help export BLT targets

### ISSUE THREAD

**Issue by white238** [LLNL/blt#552]
#526 exposed that it would be helpful to minimize the copy/paste code all of our projects that export BLT targets have to do.  For example,

https://github.com/LLNL/axom/blob/482749b322057ca7ef9a6d786e948692d9f72246/src/cmake/thirdparty/SetupAxomThirdParty.cmake#L240-L256

This should be internal to BLT and would allow us to change internal targets easier and not expose that to the downstream customers.

`blt_export_targets(NAMESPACE myproject)`

**Comment by davidbeckingsale** [comment]
I love this. I can look at it.

**Comment by white238** [comment]
maybe even something like:

```
blt_export_targets(NAMESPACE myproject
                              TARGETS       ${myproject_targets}
                              EXPORT_BLT_TARGETS True)
```

**Comment by trws** [comment]
This is in right @white238?

**Comment by white238** [comment]
Yes, @davidbeckingsale created a new macro `blt_export_tpl_targets(EXPORT <export-set> NAMESPACE <namespace>)` in #556.

Closing this ticket.  If there is an issue with this target we should create a new issue.
