### ISSUE TITLE
Corona allocate may be causing quartz build steps to not start

### ISSUE THREAD

**Issue by white238** [LLNL/blt#571]
![Screenshot 2022-03-17 155627](https://user-images.githubusercontent.com/595301/158907586-897194b7-0268-46e1-9e95-813b0d6899ae.png)

**Comment by white238** [comment]
This pipeline is currently just sitting for over 39 minutes. https://lc.llnl.gov/gitlab/blt/blt/-/pipelines/155188

**Comment by rhornung67** [comment]
@white238 why are the allocate/release, build/test steps interleaved for various platforms like that? For RAJA, it looks like this: https://lc.llnl.gov/gitlab/radiuss/RAJA/-/pipelines/154795

**Comment by white238** [comment]
i dont think that is the problem.  My understanding was those are stages and are not connected in that way (though the UI is not helpful).  The triggering of jobs inside of a pipeline are not dependent on the entire previous stage being complete.

i think it has to do with the variable `PROJECT_ALLOC_NAME` name being used across machines... maybe?

**Comment by rhornung67** [comment]
Dunno. You would know better than me.
