### ISSUE TITLE
CMake fails with library that uses cuda and object library

### ISSUE THREAD

**Issue by mclarsen** [LLNL/blt#60]
`  blt_add_library(
        NAME        vtkh_par
        SOURCES     ${vtkh_sources} ${vtkh_par_sources} $<TARGET_OBJECTS:lodepng>
        HEADERS     ${vtkh_par_headers}
        DEPENDS_ON  ${vtkh_thirdparty_libs} mpi icet)`

This works without CUDA, but fails when one of the thirdparty_libs is CUDA.

`Call Stack (most recent call first):
  blt/cmake/thirdparty/FindCUDA.cmake:1723 (CUDA_WRAP_SRCS)
  blt/cmake/BLTMacros.cmake:332 (cuda_add_library)
  vtk-h/CMakeLists.txt:96 (blt_add_library)`

`CMake Error at blt/cmake/BLTMacros.cmake:392 (get_source_file_property):
  Cannot find source file:`

    `$<TARGET_OBJECTS:lodepng>`

  `Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx`
`Call Stack (most recent call first):`
  `vtk-h/CMakeLists.txt:96 (blt_add_library)`

`CMake Error at blt/cmake/thirdparty/FindCUDA.cmake:1548 (add_custom_command):
  add_custom_command called with OUTPUT containing a "<".  This character is
  not allowed.`
`Call Stack (most recent call first):
  blt/cmake/thirdparty/FindCUDA.cmake:1723 (CUDA_WRAP_SRCS)
  blt/cmake/BLTMacros.cmake:332 (cuda_add_library)
  vtk-h/CMakeLists.txt:130 (blt_add_library)
`

**Comment by white238** [comment]
I am pretty sure this is solved in the new object library support or is at least not necessary to do.
