### ISSUE TITLE
Update the version of gbenchmark

### ISSUE THREAD

**Issue by TotoGaz** [LLNL/blt#604]
Hello,

When using BLT we use the embedded google benchmark which is currently at version 1.5.0.
With recent compilers (e.g. clang13, and I've been told gcc12), we face some "_unused variable error_" (https://github.com/google/benchmark/issues/1172)
```c++
/Users/travis/build/GEOSX/GEOSX/src/cmake/blt/thirdparty_builtin/benchmark-1.5.0/src/complexity.cc:85:10: error: variable 'sigma_gn' set but not used [-Werror,-Wunused-but-set-variable]
  double sigma_gn = 0.0;
```
which was fixed in the latest release of google benchmark 1.7.0 (https://github.com/google/benchmark/pull/1174) see https://github.com/google/benchmark/blob/v1.7.0/src/complexity.cc

Could you upgrade such that we're able to build seamlessly?

Thx!

**Comment by white238** [comment]
Fixed in #627
