### ISSUE TITLE
Do we still need CMP0076 set to old?

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#611]
Using newer cmake, we always get depreciation warning related to BLT's choice of old for CMP0076

```
CMake Deprecation Warning at blt/SetupBLT.cmake:87 (cmake_policy):
  The OLD behavior for policy CMP0076 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  cmake/SetupBLT.cmake:40 (include)
  CMakeLists.txt:113 (include)
```

https://github.com/LLNL/blt/blob/8c229991e65e7a9603c621b47cb3ba158bb7468c/SetupBLT.cmake#L87

Seems any header only issues should be resolved with build vs install interface target settings?

**Comment by chapman39** [comment]
any updates on this?

**Comment by ibaned** [comment]
I would also like to have a resolution to this, it seems like an inappropriate code smell for the central CMake toolbox at Livermore to be emitting these warnings in all downstream projects, especially given the "will be removed from a future version" part of the warning.
