### ISSUE TITLE
Error when blt_add_code_checks calls blt_add_yapf_target

### ISSUE THREAD

**Issue by chapman39** [LLNL/blt#624]
Having this issue in LiDO where when I call `blt_add_code_checks` I get the following error:

```
CMake Error at cmake/blt/cmake/SetupCodeChecks.cmake:873 (message):
  blt_add_yapf_target requires a SRC_FILES parameter
Call Stack (most recent call first):
  cmake/blt/cmake/SetupCodeChecks.cmake:246 (blt_add_yapf_target)
  CMakeLists.txt:187 (blt_add_code_checks)
```

The `SRC_FILES` variable is set to `_py_sources` (retrieved from `blt_split_source_list_by_language`, see https://github.com/LLNL/blt/blob/develop/cmake/SetupCodeChecks.cmake#L156).

I guess when `blt_split_source_list_by_language` is called, `Python_LIST` is empty, which means `_py_sources` is empty, which means `SRC_FILES` is `""` when it gets down to `blt_add_yapf_target`.

When I commented out the fatal error I was able to make by LiDO build without issues. Maybe this check is not required?

**Comment by white238** [comment]
I see two solutions:

1) Have the user required to not provide a YAPF config file if you don't provide Python files to add code checks for (this seems less than robust).

2) Check on each of these if blocks that you are actually providing source files to run checks for:
https://github.com/LLNL/blt/blob/92450b0d4e4ccb534b9f69b6214ab31633cdd9d1/cmake/SetupCodeChecks.cmake#L238-L255

I would lean towards the second option.
