### ISSUE TITLE
BLT v0.5.3 has some build errors related to googletest

### ISSUE THREAD

**Issue by adayton1** [LLNL/blt#649]
Reproducer:
* Log onto rzansel
* git clone git@github.com:LLNL/CARE.git
* cd CARE/blt && git checkout v0.5.3
* cd ../ && mkdir build && cd build
* cmake -C ../configs/lc/blueos_3_ppc64le_ib_p9/nvcc_clang.cmake ../
* lalloc 1 lrun -1 make

Here's a link to the config file: https://github.com/LLNL/CARE/blob/develop/configs/lc/blueos_3_ppc64le_ib_p9/nvcc_clang.cmake

Error:

```
[ 18%] Building CUDA object blt/tests/smoke/CMakeFiles/blt_cuda_gtest_smoke.dir/blt_cuda_gtest_smoke.cpp.o
/g/g17/dayton8/ale3d/github_care_4/blt/thirdparty_builtin/googletest/googletest/include/gtest/gtest-matchers.h(398): error: namespace "std" has no member "is_trivially_copy_constructible"
          detected during:
            processing of template argument list for "testing::internal::MatcherBase<T>::ValuePolicy [with T=const std::string &]" based on template argument <MM> 
(447): here
            instantiation of "void testing::internal::MatcherBase<T>::Init(M &&) [with T=const std::string &, M=const testing::MatcherInterface<const std::string &> *&]" 
(276): here
            instantiation of "testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U> *) [with T=const std::string &, U=const std::string &]" 
(500): here

/g/g17/dayton8/ale3d/github_care_4/blt/thirdparty_builtin/googletest/googletest/include/gtest/gtest-matchers.h(398): error: type name is not allowed
          detected during:
            processing of template argument list for "testing::internal::MatcherBase<T>::ValuePolicy [with T=const std::string &]" based on template argument <MM> 
(447): here
            instantiation of "void testing::internal::MatcherBase<T>::Init(M &&) [with T=const std::string &, M=const testing::MatcherInterface<const std::string &> *&]" 
(276): here
            instantiation of "testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U> *) [with T=const std::string &, U=const std::string &]" 
(500): here

/g/g17/dayton8/ale3d/github_care_4/blt/thirdparty_builtin/googletest/googletest/include/gtest/gtest-matchers.h(398): error: the global scope has no "value"
          detected during:
            processing of template argument list for "testing::internal::MatcherBase<T>::ValuePolicy [with T=const std::string &]" based on template argument <MM> 
(447): here
            instantiation of "void testing::internal::MatcherBase<T>::Init(M &&) [with T=const std::string &, M=const testing::MatcherInterface<const std::string &> *&]" 
(276): here
            instantiation of "testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U> *) [with T=const std::string &, U=const std::string &]" 
(500): here

3 errors detected in the compilation of "/g/g17/dayton8/ale3d/github_care_4/blt/tests/smoke/blt_cuda_gtest_smoke.cpp".
```

**Comment by white238** [comment]
Can I see the full compile line? What C++ standard are you ending up with? The new gtest requires 14 but there is a check for that so I am confused how that could happen:

https://github.com/LLNL/blt/blob/4e1fa86639496e30a22cc10eaf0cd199bcc53008/thirdparty_builtin/CMakeLists.txt#L8-L14

@rhornung67 that gcc4.9.3 is an exclude, it is removing that old version.

**Comment by rhornung67** [comment]
@white238 yes, you are correct sir! My advanced age has affected my ability to read.... 😞

**Comment by adayton1** [comment]
Here's the full compile line:

/usr/tce/packages/cuda/cuda-11.7.0/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/tce/packages/clang/clang-ibm-14.0.5/bin/clang++ -DGTEST_HAS_DEATH_TEST=0 -isystem=/path/to/blt/thirdparty_builtin/googletest/googletest/include -isystem=/usr/tce/packages/cuda/cuda-11.7.0/include -O3 -DNDEBUG --generate-code=arch=compute_70,code=[compute_70,sm_70] -Xcompiler=-fPIE -std=c++14 -MD -MT blt/tests/smoke/CMakeFiles/blt_cuda_gtest_smoke.dir/blt_cuda_gtest_smoke.cpp.o -MF CMakeFiles/blt_cuda_gtest_smoke.dir/blt_cuda_gtest_smoke.cpp.o.d -x cu -rdc=true -c /path/to/blt/tests/smoke/blt_cuda_gtest_smoke.cpp -o CMakeFiles/blt_cuda_gtest_smoke.dir/blt_cuda_gtest_smoke.cpp.o

**Comment by kennyweiss** [comment]
@adayton1 -- I ran into this w/ axom here -- https://github.com/LLNL/axom/pull/1120

GTest changed how they handle `GTEST_HAS_DEATH_TESTS` -- they either want it defined (`#ifdef`) or not (`#ifndef`) rather than checking for the value to be 0 or 1.  See: https://github.com/google/googletest/commit/dc10c3b5e55c1101e7759bdb7bf9790cebbf4ad2

Axom only had file where that definition went wonky, so I hacked together an ugly fix: https://github.com/LLNL/axom/pull/1120/files#diff-f275c47d3d694fa090c7cccbb29de43d860accc5471d0c5247b4b2e78a7476b6

I also ran into oddities with the new `GMock` in blt@0.5.3 and had to develop a workaround for the `MATCHER_P` macro: https://github.com/LLNL/axom/pull/1120/files#diff-f275c47d3d694fa090c7cccbb29de43d860accc5471d0c5247b4b2e78a7476b6

**Comment by adayton1** [comment]
Is there a way we can fix this in BLT without requiring every project to do some fixes like this?

**Comment by white238** [comment]
Add this to your host-config and it makes it go away:

```
set(CMAKE_CUDA_FLAGS "-Xcompiler=--gcc-toolchain=${GCC_HOME}" CACHE STRING "")
```

I will add an example in BLT's host-configs.  The current example host-configs have gcc 8.3.1 built in and do not rely on the `gcc-toolchain` flag on blueos.
