### ISSUE TITLE
 blt_add_yapf_target requires a SRC_FILES parameter

### ISSUE THREAD

**Issue by drmichaeltcvx** [LLNL/blt#693]
Hello, 

I am building GEOS that uses BLT and during configuration of the GEOS itself I am getting these types of messages:

```
CMake Error at cmake/blt/cmake/SetupCodeChecks.cmake:871 (message):
  blt_add_yapf_target requires a SRC_FILES parameter
Call Stack (most recent call first):
  cmake/blt/cmake/SetupCodeChecks.cmake:244 (blt_add_yapf_target)
  CMakeLists.txt:373 (blt_add_code_checks)
```
I am using GCC 13.2.0 on RHEL8-like OS (Alma8) and OpenMPI off HPC-X v2.18. Python comes from Anaconda 2042.02 and Python v 3.11.7.

Cmake v3.28.3

How is SRC_FILES parameter used and what could be causing this error?

Thanks!

**Comment by white238** [comment]
YAPF is a python formatter. It is being automatically detected by BLT, which now reminds me I should probably remove that automatically turning on behavior in our upcoming breaking change release.

Assuming you don't have python files you want to format, turn it off by setting this variable before calling `include(SetupBLT.cmake)`:

```
set(ENABLE_YAPF OFF CACHE BOOL "")
```

Here is an example on how to turn off all the tools you don't need while turning on the ones you do:

https://github.com/LLNL/axom/blob/dbc3f8f89dd0b8fb38952c5e765a95c9cc96a952/src/CMakeLists.txt#L51-L78

**Comment by drmichaeltcvx** [comment]
Thanks ! Let me try to disable this option. I hope this fixes it.

**Comment by drmichaeltcvx** [comment]
Indeed, after setting `set(ENABLE_YAPF OFF CACHE BOOL "")` GEOS builds completely.

Thank you for the prompt response!

**Comment by white238** [comment]
No problem. Glad it helped.
