### ISSUE TITLE
Setting `CMAKE_RUNTIME_OUTPUT_DIRECTORY` causing duplicate exec issues when building MFEM with Ninja

### ISSUE THREAD

**Issue by chapman39** [LLNL/blt#695]
BLT is setting `CMAKE_RUNTIME_OUTPUT_DIRECTORY` in `SetupBLT.cmake` to `${PROJECT_BINARY_DIR}/bin` [here](https://github.com/LLNL/blt/blob/develop/SetupBLT.cmake#L158-L162), which may cause duplication issues if tests of the same project have the same exec name but intend for them to be in different directories. This occurs when configuring MFEM with Ninja.

## Error message

```
...

-- Configuring done
-- Generating done
CMake Error:
  Running

   '/usr/tce/packages/python/python-3.9.12/bin/ninja-build' '-C' '/usr/workspace/meemee/lido-2.0/repo/build/build1' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:7480: multiple rules generate bin/ex9 [-w dupbuild=err]

...
```

## How to replicate this issue via MFEM

* Clone mfem and create a build dir
* Modify `config/user.cmake` to the following

```cmake
set(SUNDIALS_DIR "<any sundials build>" CACHE PATH "")
set(MFEM_USE_SUNDIALS ON CACHE BOOL "")

# BLT Bug(?)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY
  ${PROJECT_BINARY_DIR}/bin
  CACHE PATH
  "Directory where executables will go in the build tree")

set(MFEM_BUILT_WITH_CMAKE TRUE)
```

* `mkdir build && cd build && cmake .. -G Ninja`

## Comparing when set and unset

This is when `CMAKE_RUNTIME_OUTPUT_DIRECTORY` is set (one of the ex9s have been overridden!). Note this is allowed when using Make. The error only occurs when using Ninja.
```
./mfem/examples/ex9p
./mfem/examples/ex9
```

This is when `CMAKE_RUNTIME_OUTPUT_DIRECTORY` is unset:
```
./mfem/examples/sundials/ex9p
./mfem/examples/sundials/ex9
./mfem/examples/ex9p
./mfem/examples/ex9
```

## Solution

I am not sure what the best approach for this problem is. MFEM does not seem to want to change this https://github.com/mfem/mfem/issues/4437 . BLT can also do nothing and just let users unset the cached variable after calling `SetupBLT.cmake`, but it might take time for users to figure out this sort of error.

**Comment by white238** [comment]
This is an unfortunate case of several project wide things hitting each other. There could be different ways to fix this. I am a bit confused why unsetting that variable changes the example directory due to it being set to `bin` not `examples`.  Could you work around this by unsetting it before loading MFEM then setting it back? I can also help inperson or webex to dig into this.

**Comment by chapman39** [comment]
I can work around it. Ill make a pr in serac.

**Comment by cyrush** [comment]
mfem could set the output dir for each of their exes.  Is this b/c you are using mfem as a sub-module and fusing the cmake build systems?

**Comment by chapman39** [comment]
In MFEM there is a `bin/sundials/ex9` and a `bin/ex9`, but when `CMAKE_RUNTIME_OUTPUT_DIRECTORY` is set, it messes that up.

Yeah Serac has an option to build MFEM as a submodule.

**Comment by cyrush** [comment]
Got it, blt make it very easy to set the target properties to change the dir when you create an exe, but MFEM isn't using BLT itself. 

Mfem could set the target properties for these exes? Set `RUNTIME_OUTPUT_DIRECTORY` to `${CMAKE_CURRENT_BINARY_DIR}`


Fused cmake build systems are scary know past and future source of pain an suffering.

**Comment by white238** [comment]
It also seems two projects had examples named the same thing so they clashed. We were able to work around this in Serac by unsetting and setting this variable around the inclusion of MFEM.

Closing for now.
