### ISSUE TITLE
create imported targets for tpls in blt_register_library

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#9]
To expose the full dependency structure to cmake, we should explore using fully described imported targets in blt_register_lib.

This already works for exported then imported lib targets for tpls built with CMake.

Make sure this also works for header only libraries and tpls that are simply registered. 

This support may require CMake version greater than 3.3.

**Comment by rrsettgast** [comment]
Did this ever get resolved? Can I ditch my old branch that had a manual -isystem include option?

https://lc.llnl.gov/jira/projects/ATK/issues/ATK-779

**Comment by cyrush** [comment]
@rrsettgast, not yet there is still work to be done. However now that CMake 3.8 is out, we are hopeful it is possible. There were some road blocks (related to header only libs) that requried a new version of cmake -- and vers 3.4 <--> 3.7 had other bugs (related to python and hdf5) that stopped us from upgrading.

**Comment by white238** [comment]
I'm pretty sure this was fixed in the `blt_import_library` PR a long time ago.
