### ISSUE TITLE
Would be nice if blt used BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by tepperly** [LLNL/blt#99]
It would be nice if blt supported [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.4/variable/BUILD_SHARED_LIBS.html?highlight=build_shared_libs]) instead of requiring -DENABLE_SHARED_LIBS. Or perhaps, the default for ENABLE_SHARED_LIBS should come from BUILD_SHARED_LIBS instead of being false.

**Comment by cyrush** [comment]
@tepperly, I agree BUILD_SHARED_LIBS seems to be more widely used. 

For conduit, I work around this with the following logic before including blt:

```
option(BUILD_SHARED_LIBS  "Build shared libraries"      ON)
# forward conduit's build shared libs option to blt
set(ENABLE_SHARED_LIBS ${BUILD_SHARED_LIBS} CACHE BOOL "")

```

**Comment by zbeekman** [comment]
I'm going to submit a PR for this. I won't be offended if you mark as won't fix or want to handle it some other way.

**Comment by davidbeckingsale** [comment]
👍
